Story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='index'),
    path('gallery/', views.gallery, name='gallery'),
    # dilanjutkan ...
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
	return render(request, 'Home.html')

def gallery(request):
	return render(request, 'music-gallery.html')

home/templates/Home.html
<!DOCTYPE html>

{% load static %}

<html lang= "en">



<head>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <!--  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> -->
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.css' %}" />
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/main.css' %}" >
  <link href ="https://fonts.googleapis.com/css?family=Proxima+Nova" rel="stylesheet">
  <link href ="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">

   <meta name="viewport" content="width=device-width, initial-scale=1">
	<title> Personal Website </title>
</head>
<body style="max-width:100% ">

   <nav id="nav1" class="navbar navbar-expand-md bg-dark navbar-dark fixed-top" style="position:fixed;top:0px;">
        <a class="navbar-brand" href="#" style="position:relative;left:30px;">Nevil's website</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar" >
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#skills">Hobby & Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#education">Educational background</a>
                </li>  
                <li class="nav-item">
                    <a class="nav-link" href="#schedule">Schedule & Contact</a>
                </li>  
            </ul>
        </div>  
    </nav>


<div style="height:50px;">
<h1 id="about" style="position:relative;top:35px;"></h1>
</div>

<div style="background-image: url('/static/images/sky.jpg');font-family:Arial;height:420px;"> 

<h2 id="about-title" > About me </h2>
<p id="about-msg"> 
 An Information System <br>
 Student at Faculty of <br>
 Computer Science, <br>
 Universitas Indonesia </p>
<img src="{% static 'images/jerapah.jpg' %}" alt="jerapah" width="530" height="400" style="position:relative;left:700px; bottom:150px">


</div>

<div style="background-color:white;height:250px" > 
	<h1 id="skills"> <b> Hobby & Skills </b></h1>
</div>
    <div class="container-fluid">
      <div style="background-image: url('slark1.jpg');height:310px;position:relative;top:10px">
      	<img src="{% static 'images/button 1.jpg' %}" alt="gaming" width="250" height="250" style="position:relative; left:100px;top:30px">
      	<img src="{% static 'images/button 2.jpg' %}" alt="java" width="250" height="250" style="position:relative;left:150px;top:30px">
      	<img src="{% static 'images/button 3.jpg' %}" alt="piano" width="250" height="250" style="position:relative;left:200px;top:30px">
      	<img src="{% static 'images/HTML.jpg' %}" alt="html" width="250" height="250" style="position:relative;left:250px;top:30px">
      </div>
    </div>

<div style="background-color:white;height:310px">
	<h1 style="position:relative;top:20px"> <b> Favorite Foods & Drinks </b></h1>

	<img src="{% static 'images/rendang.jpg' %}" alt="rendang" width="170" height="170" style="position:relative;top:30px;left:250px">
	<img src="{% static 'images/pizza.jpg' %}" alt="pizza" width="170" height="170" style="position:relative;top:30px;left:300px;">
	<img src="{% static 'images/icecream.jpg' %}" alt="eskrim" width="170" height="170" style="position:relative;top:30px;left:350px;">
	<img src="{% static 'images/kopi.jpg' %}" alt="kopi" width="170" height="170" style="position:relative;top:30px;left:400px;">
</div>

<div style="background-color:white;height:100px">
	<h1 id="education"> <b> Educational Background </b> </h1>

</div>


<div style="background-image: url('road1.jpg'); height:370px;">
	<img src="{% static 'images/SMP.jpg' %}" alt="photo of JHS" width="300" height="270" style="position:relative;top:55px;left:140px">
	<img src="{% static 'images/SMA.jpg' %}" alt="photo of SHS" width="300" height="270" style="position:relative;top:55px;left:190px">
	<img src="{% static 'images/rektorat.jpg' %}" alt="photo of univ" width="320" height="270" style="position:relative;top:55px;left:240px">
</div>

<div style="background-color:white; height:100px">
	<img src="{% static 'images/lifeline1.jpg' %}" alt="lifeline" width="1100" height="180" style="position:relative;left:130px">
</div>

<div style="background-color:white;height:800px">
	<h1 id="schedule"> <b> Class Schedule </b> </h1>
	<img src="{% static 'images/jadwal.jpg' %}" alt="Schedule" width="1000" height="410" style="position:relative;left:180px;top:225px" >
</div>

<div style="background-color: black;height:200px;max-width:100%">
	<h2 style="color:white;position:relative;left:40px;top:20px;width:300px"> Contact: </h2>
	<a href="https://www.facebook.com/nevil.ns/" target="_blank"> <img src="{% static 'images/fb.jpg' %}" alt="fb logo" width="60" height="60" style="position:relative;left:30;top:30;"> </a>

	<a href="https://instagram.com/nevil_philia?igshid=1im7mvgiylwv3" target="_blank"><img src="{% static 'images/instagram.jpg' %}" alt="ig logo" width="60" height="60" style="position:relative;left:40;top:30;"> </a>
	<img src="{% static 'images/line.jpg' %}" alt="line logo" width="60" height="60" style="position:relative;left:50;top:30;">
	<p style="position:relative;left:250px;bottom:35px;color:white;font-size:20px;width:300px"> Line ID: </p>
	<p style="position:relative;left:250px;bottom:55px;color:white;font-size:24px;width:300px"> nevilphilia </p>
	<a href="{% url 'home:gallery' %}" id="view-gallery"> <b> View Music Gallery </b> </a>

</div>



<script>
var prevScrollpos = window.pageYOffset;
window.onscroll = function() {
var currentScrollPos = window.pageYOffset;
  if (prevScrollpos > currentScrollPos) {
    document.getElementById("nav1").style.top = "0";
  } else {
    document.getElementById("nav1").style.top = "-100";
  }
  prevScrollpos = currentScrollPos;
}
</script>
</body>

</html>

home/templates/music-gallery.html
<html >
{%load static%}
<head>
	<link rel = "stylesheet"
   type = "text/css"
   href = "{% static 'bootstrap.css' %}" />
	<link href="https://fonts.googleapis.com/css?family=Proxima+Nova" rel="stylesheet">
	<style>
		#Gallery{
			color:black;
			border-radius:50px;
			background-color:white;
			width:360px;
			font-size: 33px;
			font-family: Proxima Nova;
			text-align: center;
			padding-top:15px; 
			padding-bottom:15px;
			position:relative;
			left:460px;
			top:50px;

		}
		div{
			width:1000px;

		}
		#rumah{
			position:relative;
			bottom:30px;
			left: 75px;

		}
		#quote{
			position:relative;
			left:445px;
			bottom:370px;
			color:white;
			width:500px;
		}
		#title{
			font-family: Proxima Nova;
			font-size:40px;
			position:relative;
			left: 445px;
			bottom:360px;
			color:#95989c;
			width:300px;
		}
		#player{
			position:relative;
			left:80px;
		}
		#bill{
			position:relative;
			left:660px;
			bottom:70px;
		}
		#div2{
			height:350px;
		}

	</style>
	<title> Music Gallery </title>
</head>
<body style="background-color:black;max-height:100%">

<div>
<p style="" id="Gallery"> <b> Music Gallery </b> </p>

<a href="{% url 'home:index' %}"><img src="{% static 'images/home.jpg' %}" alt='rumah' id="rumah" height="50" width="50"></a>
</div>

<div id="div2"> 
	<iframe src="https://open.spotify.com/embed/playlist/4genODmrARTmzkuGSjYLId" width="300" height="280" frameborder="0" allowtransparency="true" allow="encrypted-media" id="player"></iframe>

	<img src="{% static 'images/bill e.jpg' %}" alt="bill-evans" width="280" height="400" id="bill">
	<p id="title"> <b> Bill Evans </b> </p>
	<p id="quote"> was an American jazz pianist and composer who mostly <br> played in trios. His use of impressionist harmony, inventive <br> interpretation of traditional jazz repertoire, block chords, and <br>trademark rhythmically independent, "singing" melodic <br>lines continue to influence jazz pianists today.  </p>
</div>

</body>
</html>